exclude: '.*/vendor/.*'
repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.6.4
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: check-added-large-files
            args: ['--maxkb=128']
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
            exclude: fixtures/.*
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
            # CloudFormation templates rely on macros which will fail a simple
            # YAML load, which is why we have cfn-python-lint enabled below:
            exclude: cloudformation/.*
          - id: debug-statements
          - id: detect-aws-credentials
            args: ['--allow-missing-credentials']
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ['--fix=lf']
          - id: pretty-format-json
            args: ['--autofix', '--no-sort-keys', '--indent=4']
            exclude: fixtures/.*
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.1.2
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md|yaml|yml)$
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v7.13.0-1
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint-plugin-prettier@^3.3.1
                - eslint-plugin-unicorn@^26.0.0
                - eslint@^7.17.0
                - prettier@^2.2.1
    - repo: https://github.com/awebdeveloper/pre-commit-stylelint
      rev: 0.0.2
      hooks:
          - id: stylelint
            additional_dependencies:
                - 'stylelint@^13.8.0'
                - 'stylelint-config-prettier@^8.0.2'
                - 'stylelint-config-recommended@^3.0.0'
                - 'stylelint-value-no-unknown-custom-properties@^3.0.0'
    - repo: https://github.com/awslabs/cfn-python-lint
      rev: v0.41.0
      hooks:
          - id: cfn-python-lint
            files: cloudformation/.*\.(json|yml|yaml)$
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
    - repo: https://github.com/PyCQA/bandit
      rev: 1.6.2
      hooks:
          - id: bandit
