extends:
    - stylelint-config-recommended
    - stylelint-config-prettier

plugins:
    - stylelint-value-no-unknown-custom-properties

rules:
    no-descending-specificity: null
    at-rule-no-unknown: null
    csstools/value-no-unknown-custom-properties: true
